name: test

on: workflow_call

jobs:
  test:
    name: Run the package tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba and install dependencies
        uses: mamba-org/setup-micromamba@v2
        with:
          init-shell: bash
          environment-name: geomappy-tests-env
          environment-file: environment.yml

      - name: Locally install geomappy
        shell: bash -l {0}
        run: |
          micromamba activate geomappy-tests-env
          python -m pip install -e .    

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba activate geomappy-tests-env
          python -c "import geomappy"
